export {
    LOAD_BOOKS_FROM_SERVER,
    Mark_BOOK_AS_READ,
    Mark_BOOK_AS_UNREAD,
    ADD_BOOK,
    DELETE_BOOK,
    TOGGLE_IS_LOADING_BOOKS,
    UPDATE_BOOK_IMAGE,
    SEARCH_BOOK,
    SEARCH_MORE_BOOK
}
const LOAD_BOOKS_FROM_SERVER = "LOAD_BOOKS_FROM_SERVER"
const Mark_BOOK_AS_READ = "Mark_BOOK_AS_READ"
const Mark_BOOK_AS_UNREAD = "Mark_BOOK_AS_UNREAD"
const ADD_BOOK = "ADD_BOOK"
const DELETE_BOOK = "DELETE_BOOK"
const TOGGLE_IS_LOADING_BOOKS = "TOGGLE_IS_LOADING_BOOKS"
const UPDATE_BOOK_IMAGE = "LOAD_BOOKS_FROM_SERVER"
const SEARCH_BOOK = "SEARCH_BOOK"
const SEARCH_MORE_BOOK = "SEARCH_MORE_BOOK"



